In [53]:
import numpy as np
import math

In [477]:
import sys
sys.path.append("/Users/lality/projects/personal/ML_Algo/")

In [501]:
from ml.tools import *

In [459]:
class l2_regularization:
    def __init__(self, lmda):
        self.lmda = lmda
        
    def __call__(self, theta):
        m = len(theta)
        return 0.5 * (self.lmda / m) * np.asscalar(theta[1:].T.dot(theta[1:]))
    
    def gradient(self, theta):
        m = len(theta)
        return (self.lmda / m) * theta

In [522]:
class Regression:
    def __init__(self, n_iteration=3000, learning_rate = 0.01):
        self.n_iteration = n_iteration
        self.learning_rate = learning_rate
        self.epsilon = 1e-3
        
    def _initialize_weight(self, n_features):
        limit = 1 / math.sqrt(n_features)
        self.theta = np.zeros((n_features, ), dtype=np.float32) # np.random.uniform(-limit, limit, (n_features, ))
        
    def _compute_cost(self, y, y_pred, m):
        J = 0
        J = (1 / (2 * m)) * np.asscalar(np.dot((y_pred - y), (y_pred - y).T))
#         J = (1.0 / (2.0 * m)) * np.sum(np.square(y_pred - y))
        return np.round(J, 2)
        
    def fit(self, X, y):
        X = np.array(X, dtype=np.float32)
        y = np.array(y, dtype=np.float32)
        X = np.round(X, 2)
        y = np.round(y, 2)
        X = np.insert(X, 0, 1, axis=1)
        m = np.size(y)
        self.J_iterations = []
        self._initialize_weight(n_features=X.shape[1])
        J_current = 100.0
        J_prev = 100.0
        for _ in np.arange(self.n_iteration):
            y_pred = X.dot(self.theta)
            J_prev = J_current
            
            J_current = self._compute_cost(y, y_pred, m)
            
            self.J_iterations.append(J_current)
            gradient =  (1.0/m) * (X.T.dot(y_pred - y))
#             print(J_current, gradient)
#             if J_prev  - J_current < self.epsilon: break
            self.theta -= self.learning_rate * np.round(gradient, 2)
            
    def predict(self, X):
        X = np.array(X, dtype=np.float32)
        X = np.round(X, 2)
        X = np.insert(X, 0, 1, axis=1)
        y_pred = X.dot(self.theta)
        return y_pred

In [531]:
class PolynomialRegression(Regression):
    def __init__(self, degree, n_iterations=300, learning_rate=0.01):
        self.degree = degree
        super(PolynomialRegression, self).__init__(n_iterations, learning_rate)
    
    def fit(self, X, y):
        X = poly_feature(X, degree=self.degree).values
        super(PolynomialRegression, self).fit(X, y)
        
    def predict(self, X):
        X = poly_feature(X, degree=self.degree).values
        return super(PolynomialRegression, self).predict(X)

In [537]:
p.theta

array([-2.0379706e+07, -8.2754704e+07, -3.5872736e+08], dtype=float32)

In [533]:
def poly_feature(X, degree):
    poly_frame = pd.DataFrame()
    poly_frame['power_1'] = X
    for power in range(2, degree+1):
        name = 'power_' + str(power)
        poly_frame[name] = X ** power
    return poly_frame

In [534]:
p = PolynomialRegression(degree = 2)
p.fit(X, y)
y_pred = p.predict(np.array([7, 9])); y_pred

array([-1.8177303e+10, -2.9822087e+10], dtype=float32)

In [530]:
poly_feature(X, degree=2).values

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25]])

In [536]:
p.theta

array([-2.0379706e+07, -8.2754704e+07, -3.5872736e+08], dtype=float32)

In [446]:
from sklearn.linear_model import LinearRegression

In [513]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

In [515]:
model = make_pipeline(PolynomialFeatures(degree=2), LinearRegression())

In [517]:
model.fit(X.reshape(-1, 1), y)

Pipeline(memory=None,
     steps=[('polynomialfeatures', PolynomialFeatures(degree=2, include_bias=True, interaction_only=False)), ('linearregression', LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False))])

In [519]:
model.predict(np.array([7, 9]).reshape(-1, 1))

array([49., 81.])

In [447]:
X = np.array([1, 2, 3, 4, 5])
y = np.array([1, 4, 9, 16, 25])

In [464]:
X = np.insert(X, 0, 1, axis=1)

In [448]:
X = X.reshape((X.shape[0], -1))

In [465]:
y_pred = X.dot(r.theta)

In [466]:
(1.0/m) * (X.T.dot(y_pred - y))

array([ 0.00354998, -0.00095006])

In [460]:
r.theta

array([-5.324001,  5.536   ], dtype=float32)

In [461]:
l = l2_regularization(0.1)
l.gradient(r.theta)

array([-0.26620004,  0.2768    ], dtype=float32)

In [467]:
((1.0/m) * (X.T.dot(y_pred - y))) + l.gradient(r.theta)

array([-0.26265005,  0.27584994])

In [233]:
from sklearn.metrics import r2_score

In [239]:
r2_score(y_test, t)

-66.36287754552649

In [204]:
from sklearn.linear_model import LinearRegression

In [240]:
lm = LinearRegression()
lm.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [241]:
prd = lm.predict(X_test)

In [242]:
r2_score(y_test, prd)

-0.3720700299809594

In [244]:
print(lm.intercept_, lm.coef_)

28.67259959085611 [-1.91246374e-01  4.42289967e-02  5.52207977e-02  1.71631351e+00
 -1.49957220e+01  4.88773025e+00  2.60921031e-03 -1.29480799e+00
  4.84787214e-01 -1.54006673e-02 -8.08795026e-01 -1.29230427e-03
 -5.17953791e-01]


In [124]:
theta = np.random.uniform(-limit, limit, (14, ))

In [468]:
theta

array([1.65597003e+00, 3.54678165e+00, 2.22904548e+01, 1.54365373e+01,
       3.15790381e-01, 9.50749208e-01, 9.66584184e+00, 1.01696856e+02,
       6.17962647e+00, 1.15642337e+01, 5.72600044e+02, 2.78872439e+01,
       5.91587323e+02, 1.77602886e+01])

In [132]:
y_pred = X.dot(theta)

In [134]:
m = len(y)

In [135]:
(1 / (2 * m)) * np.asscalar(np.dot((y_pred - y), (y_pred - y).T))

12413.88404589118

In [138]:
g = (1/m) * (X.T.dot(y_pred - y))

In [139]:
theta = theta - 0.01 * g

In [471]:
np.linalg.norm([1, 2, 3, 4, 5])

7.416198487095663

In [472]:
np.sum([1, 2, 3, 4, 5])

15

In [473]:
np.sign([1, 2, 3, 4, 5])

array([1, 1, 1, 1, 1])

In [474]:
np.sign([1, 2, 3, 0.4, 5])

array([1., 1., 1., 1., 1.])

In [475]:
np.sign([1, 2, 3, -4, 5])

array([ 1,  1,  1, -1,  1])

In [476]:
np.sign([1, 2, 3, 0, 5])

array([1, 1, 1, 0, 1])

In [ ]:
np.mean